### ISSUE TITLE
 No description, website, or topics provided.

### ISSUE THREAD

**Issue by 1000i100** [onenationxyz/onenation#1]
En haut de la page github, il n'y a pas de lien vers le site, alors que je vois souvent cette usage, et qu je le trouve pratique ;)

De même, si ce dépot a pour vocation principale le site, pourquoi ne pas mettre la branche gh-pages en branche par défaut ? d'autant que c'est actuellement la plus à jour (et du coup lui inclure un readme.md).

Belle initiative en tout cas !

**Comment by onenationxyz** [comment]
Merci pour ton message !
Tout ça est en train d’être cleané 😅  ça devrait être publié d’ici la fin du week-end.
Il y a tellement à faire !

Normalement à partir de ce week-end le github sera vraiment opérationnel pour y travailler à plusieurs.

Trop cool tu est le premier message sur github 🥳

**Comment by Nicolas-2A** [comment]
Bonjour à vous, je veux vous accompagner. Je ne sais pas en quoi je serais le plus utile mais je vais déjà commencer par donner de mon temps. Un grand bravo d'avoir lancé un tel projet qui est disons le, de plus en plus une nécessité.

**Comment by hel974** [comment]
Bonjour, je ne comprends rien à github pour le moment mais c'est super d'être ici! comment peut on aider? Bravo Onenation d'être et d'impulser aussi bien un tel mouvement! première fois que je m'engage dans un groupe quel qu'il soit tellement je répugne à "faire partie" en général car c'est toujours limitant de "faire partie" d'un groupe.. Mais là je ne ressens pas de fermeture ni d'intolérance, je me sentirai presque chez moi!

**Comment by sylvain441** [comment]
Salut @Nicolas-2A et @hel974.
La plupart des gens s'organisent sur Telegram : https://t.me/onenation_fr_bienvenue
Ce github sert de référence, pour héberger les traductions du Manifeste et le site One Nation de façon collaborative.
Mais le cœur de One Nation c'est d'agir dans la vie physique entre humains.
Un jour je le souhaite One Nation hébergera (ou agglomérera) des solutions open source bien foutues qui feront que nous pourrons nous passer d'un millefeuille de lois absurdes, inutiles et incompréhensibles.

**Comment by hel974** [comment]
J'espère que ce jour n'est pas loin! Merci Sylvain

Helene

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------
